import { Resend } from 'resend';

// Vercel Serverless Function
export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  try {
    // Initialize Resend with the API Key set in Vercel Environment Variables
    const resend = new Resend(process.env.RESEND_API_KEY);
    
    // Get the data from the frontend fetch request
    const {
      to_email,
      message,
      attachment,
      report_id,
      reporter_name,
      facility,
      date
    } = req.body;

    // We can format a beautiful HTML email here using the data
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <h2>Notifikasi Kesilapan Pengubatan</h2>
        <p style="white-space: pre-wrap;">${message}</p>
        
        <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #ef4444; margin-top: 20px;">
          <h3 style="margin-top: 0; color: #ef4444;">Maklumat Laporan:</h3>
          <ul style="list-style: none; padding: 0;">
            <li><strong>ID Laporan:</strong> ${report_id}</li>
            <li><strong>Fasiliti:</strong> ${facility}</li>
            <li><strong>Tarikh Acara:</strong> ${date}</li>
            <li><strong>Dilapor oleh:</strong> ${reporter_name}</li>
          </ul>
        </div>
        
        <p style="margin-top: 30px; font-size: 12px; color: #888;">
          Auto-generated by MedSafety Pro System. Please do not reply to this email.
        </p>
      </div>
    `;

    // Process attachment if exists
    // The frontend sends something like: data:application/pdf;base64,JVBERi0xLj...
    // Resend requires just the pure base64 string
    const attachments = [];
    if (attachment) {
      // Split the data URI to just get the base64 part
      const base64Data = attachment.split('base64,')[1] || attachment;
      attachments.push({
        filename: `Laporan_Kesilapan_Pengubatan_${report_id}.pdf`,
        content: base64Data,
      });
    }

    // Send the email
    const data = await resend.emails.send({
      from: 'MedSafety Pro <onboarding@resend.dev>', // You must verify your own domain in Resend to change this
      to: [to_email],
      subject: `Laporan Kesilapan Pengubatan - ${report_id}`,
      html: emailHtml,
      attachments: attachments
    });

    res.status(200).json({ success: true, data });

  } catch (error) {
    console.error('Email sending error:', error);
    res.status(500).json({ success: false, error: error.message || 'Internal Server Error' });
  }
}
